### Amazon Global Sales Analysis (big data project)

In [1]:
import pandas as pd

In [8]:
df= pd.read_csv( "cleaned_dataset.csv" )
df

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue,profit
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52,23.1760
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40,60.5200
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28,39.6640
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64,63.2320
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72,40.3360
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,2022-09-03,1433,Beauty,26.99,0,5,Middle East,Credit Card,2.4,386,26.99,134.95,6.7475
49996,49997,2022-07-03,1428,Beauty,294.23,10,5,Asia,Credit Card,3.1,8,264.81,1324.05,66.2025
49997,49998,2023-02-17,4651,Electronics,352.11,30,4,Asia,Debit Card,3.1,104,246.48,985.92,49.2960
49998,49999,2022-09-30,4371,Beauty,307.54,5,1,Middle East,UPI,1.8,316,292.16,292.16,14.6080
49999,50000,2023-06-29,2944,Home & Kitchen,253.44,30,1,Europe,Debit Card,2.1,464,177.41,177.41,8.8705

In [9]:
df.head()

,order_id,order_date,product_id,product_category,price,discount_percent,quantity_sold,customer_region,payment_method,rating,review_count,discounted_price,total_revenue,profit
0,1,2022-04-13,2637,Books,128.75,10,4,North America,UPI,3.5,443,115.88,463.52,23.176
1,2,2023-03-12,2300,Fashion,302.60,20,5,Asia,Credit Card,3.7,475,242.08,1210.40,60.520
2,3,2022-09-28,3670,Sports,495.80,20,2,Europe,UPI,4.4,183,396.64,793.28,39.664
3,4,2022-04-17,2522,Books,371.95,15,4,Middle East,UPI,5.0,212,316.16,1264.64,63.232
4,5,2022-03-13,1717,Beauty,201.68,0,4,Middle East,UPI,4.6,308,201.68,806.72,40.336

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          50000 non-null  int64
 1   order_date        50000 non-null  object
 2   product_id        50000 non-null  int64
 3   product_category  50000 non-null  object
 4   price             50000 non-null  float64
 5   discount_percent  50000 non-null  int64
 6   quantity_sold     50000 non-null  int64
 7   customer_region   50000 non-null  object
 8   payment_method    50000 non-null  object
 9   rating            50000 non-null  float64
 10  review_count      50000 non-null  int64
 11  discounted_price  50000 non-null  float64
 12  total_revenue     50000 non-null  float64
 13  profit            50000 non-null  float64
dtypes: float64(5), int64(5), object(4)
memory usage: 5.3+ MB

In [13]:
df.describe()

,order_id,product_id,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue,profit
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,2986.848740,252.507260,13.340700,2.999400,2.996316,249.329280,218.886566,657.331475,32.866574
std,14433.901067,1156.374535,143.025544,9.850694,1.415401,1.154295,144.251981,127.317681,526.223968,26.311198
min,1.000000,1000.000000,5.010000,0.000000,1.000000,1.000000,0.000000,3.530000,3.840000,0.192000
25%,12500.750000,1983.000000,127.840000,5.000000,2.000000,2.000000,125.000000,109.680000,240.320000,12.016000
50%,25000.500000,2983.000000,252.970000,10.000000,3.000000,3.000000,250.000000,215.805000,505.410000,25.270500
75%,37500.250000,3989.000000,376.335000,20.000000,4.000000,4.000000,374.000000,322.702500,968.970000,48.448500
max,50000.000000,4999.000000,499.990000,30.000000,5.000000,5.000000,499.000000,499.910000,2499.550000,124.977500

In [21]:
total_revenue=df['total_revenue'].sum()
total_profit=df['profit'].sum()
print(f"Total Revenue: {total_revenue} crore")
print(f"Total Profit: {total_profit} crore")

Total Revenue: 32866573.740000002 crore
Total Profit: 1643328.687 crore

In [25]:
top_categories = df.groupby('product_category')['quantity_sold'].sum().sort_values(ascending=False)
print(top_categories)

product_category
Beauty            25422
Fashion           25089
Books             25065
Electronics       24898
Sports            24753
Home & Kitchen    24743
Name: quantity_sold, dtype: int64

In [26]:
profitable_categories = df.groupby('product_category')['profit'].sum().sort_values(ascending=False)
print(profitable_categories)

product_category
Beauty            277531.2485
Books             274243.1515
Fashion           274006.1670
Home & Kitchen    273656.6275
Electronics       273529.7015
Sports            270361.7910
Name: profit, dtype: float64

In [27]:
region_sales = df.groupby('customer_region')['total_revenue'].sum().sort_values(ascending=False)
print(region_sales)

customer_region
Middle East      8301844.50
North America    8277217.84
Asia             8175199.83
Europe           8112311.57
Name: total_revenue, dtype: float64

In [29]:
rating_analysis = df.groupby('product_category')['rating'].mean().sort_values(ascending=False)
rating_analysis

product_category
Books             3.020259
Sports            2.996891
Home & Kitchen    2.996706
Electronics       2.991298
Fashion           2.987782
Beauty            2.985186
Name: rating, dtype: float64

In [30]:
payment_method = df['payment_method'].value_counts()
payment_method

payment_method
Wallet              10106
UPI                 10078
Debit Card           9981
Cash on Delivery     9927
Credit Card          9908
Name: count, dtype: int64

In [31]:
df.groupby('discount_percent')['quantity_sold'].mean().sort_values(ascending=False)

discount_percent
20    3.028763
15    3.003369
10    2.999759
5     2.995644
0     2.986490
30    2.982241
Name: quantity_sold, dtype: float64

In [32]:
df['order_date'] = pd.to_datetime(df['order_date'])
sales_trend = df.groupby(df['order_date'].dt.month)['total_revenue'].sum()
sales_trend

order_date
1     2883926.88
2     2505094.80
3     2759003.83
4     2678973.77
5     2806178.34
6     2746947.62
7     2788265.84
8     2845629.94
9     2744974.92
10    2760754.34
11    2625428.52
12    2721394.94
Name: total_revenue, dtype: float64

In [33]:
top_products = df.groupby('product_id')['quantity_sold'].sum().sort_values(ascending=False).head(10)
print(top_products)

product_id
1087    81
1580    80
3537    79
4217    79
1617    78
2048    78
2785    77
4204    77
1386    77
3700    75
Name: quantity_sold, dtype: int64

In [36]:
df['profit_margin'] = df['profit'] / df['total_revenue']* 100
df[['profit_margin']].describe()

       profit_margin
count   5.000000e+04
mean    5.000000e+00
std     2.493261e-16
min     5.000000e+00
25%     5.000000e+00
50%     5.000000e+00
75%     5.000000e+00
max     5.000000e+00

In [37]:
pivot1 =pd.pivot_table(df, values='total_revenue', index='customer_region', columns='product_category', aggfunc='sum', fill_value=0)
pivot1

product_category,Beauty,Books,Electronics,Fashion,Home & Kitchen,Sports
customer_region,,,,,,
Asia,1401916.92,1391961.69,1319074.46,1334485.23,1369676.45,1358085.08
Europe,1358226.42,1330671.45,1407118.94,1366107.00,1326424.56,1323763.20
Middle East,1387711.96,1428560.07,1379642.77,1390228.60,1375546.52,1340154.58
North America,1402769.67,1333669.82,1364757.86,1389302.51,1401485.02,1385232.96

In [38]:
pivot2 = pd.pivot_table(df, values='rating', index='product_category', columns='customer_region', aggfunc='sum', fill_value=0)
pivot2

customer_region     Asia  Europe  Middle East  North America
product_category
Beauty            6249.6  6175.4       6333.1         6511.5
Books             6571.3  6083.2       6452.8         6042.4
Electronics       6223.1  6252.3       6170.5         6241.7
Fashion           6021.8  6352.2       6315.8         6303.0
Home & Kitchen    6265.6  6044.4       6256.7         6180.1
Sports            6193.0  6120.4       6179.1         6276.8

In [39]:
df.groupby('product_category').agg({'quantity_sold':'sum', 'total_revenue':'sum', 'profit':'sum'}).sort_values(by='total_revenue', ascending=False)

                  quantity_sold  total_revenue       profit
product_category
Beauty                    25422     5550624.97  277531.2485
Books                     25065     5484863.03  274243.1515
Fashion                   25089     5480123.34  274006.1670
Home & Kitchen            24743     5473132.55  273656.6275
Electronics               24898     5470594.03  273529.7015
Sports                    24753     5407235.82  270361.7910

In [42]:
df.groupby('product_category').agg({'total_revenue':['sum','mean' , 'max'] ,'profit':['sum', 'mean'], 'rating':['mean','sum','max']}).sort_values

<bound method DataFrame.sort_values of                  total_revenue                            profit             \
                           sum        mean      max          sum       mean
product_category
Beauty              5550624.97  655.714704  2498.85  277531.2485  32.785735
Books               5484863.03  658.684164  2492.50  274243.1515  32.934208
Electronics         5470594.03  657.523321  2492.30  273529.7015  32.876166
Fashion             5480123.34  655.125325  2483.20  274006.1670  32.756266
Home & Kitchen      5473132.55  662.767323  2493.80  273656.6275  33.138366
Sports              5407235.82  654.233009  2499.55  270361.7910  32.711650

                    rating
                      mean      sum  max
product_category
Beauty            2.985186  25269.6  5.0
Books             3.020259  25149.7  5.0
Electronics       2.991298  24887.6  5.0
Fashion           2.987782  24992.8  5.0
Home & Kitchen    2.996706  24746.8  5.0
Sports            2.996891  24769.3  5.0  >

In [45]:
pd.crosstab(df['customer_region'], df['payment_method'])

payment_method   Cash on Delivery  Credit Card  Debit Card   UPI  Wallet
customer_region
Asia                         2487         2486        2451  2606    2496
Europe                       2411         2468        2551  2478    2544
Middle East                  2544         2493        2486  2456    2526
North America                2485         2461        2493  2538    2540

In [46]:
df.corr(numeric_only=True)

,order_id,product_id,price,discount_percent,quantity_sold,rating,review_count,discounted_price,total_revenue,profit,profit_margin
order_id,1.000000,-0.004990,0.008633,-0.006286,-0.009524,0.004293,0.006928,0.010069,0.002340,0.002340,0.237126
product_id,-0.004990,1.000000,-0.001639,-0.001623,-0.002436,-0.008535,-0.009896,-0.001447,-0.004337,-0.004337,-0.008700
price,0.008633,-0.001639,1.000000,-0.004654,0.004405,0.006386,0.001282,0.974717,0.711094,0.711094,0.002900
discount_percent,-0.006286,-0.001623,-0.004654,1.000000,0.001399,0.003715,0.005193,-0.198713,-0.144392,-0.144392,0.001318
quantity_sold,-0.009524,-0.002436,0.004405,0.001399,1.000000,-0.002879,0.000717,0.004457,0.594404,0.594404,-0.000876
rating,0.004293,-0.008535,0.006386,0.003715,-0.002879,1.000000,-0.002895,0.006366,0.001804,0.001804,-0.004571
review_count,0.006928,-0.009896,0.001282,0.005193,0.000717,-0.002895,1.000000,0.000829,0.002208,0.002208,0.002243
discounted_price,0.010069,-0.001447,0.974717,-0.198713,0.004457,0.006366,0.000829,1.000000,0.729694,0.729694,0.001404
total_revenue,0.002340,-0.004337,0.711094,-0.144392,0.594404,0.001804,0.002208,0.729694,1.000000,1.000000,-0.000743
profit,0.002340,-0.004337,0.711094,-0.144392,0.594404,0.001804,0.002208,0.729694,1.000000,1.000000,-0.000743
profit_margin,0.237126,-0.008700,0.002900,0.001318,-0.000876,-0.004571,0.002243,0.001404,-0.000743,-0.000743,1.000000

In [49]:
pd.pivot_table(df,values='total_revenue',index=['product_category','customer_region'], columns='payment_method',aggfunc='sum')

payment_method                    Cash on Delivery  Credit Card  Debit Card  \
product_category customer_region
Beauty           Asia                    283496.27    270807.84   291431.42
                 Europe                  274879.98    267677.35   281102.25
                 Middle East             317443.53    273247.15   277978.17
                 North America           293307.04    291503.37   281878.68
Books            Asia                    272398.31    279647.07   281838.34
                 Europe                  271535.29    265239.86   248370.95
                 Middle East             316819.51    281739.73   269344.22
                 North America           265842.62    263885.94   253365.47
Electronics      Asia                    256496.73    262887.37   255229.98
                 Europe                  275759.56    283802.81   275405.71
                 Middle East             272088.97    297404.60   250669.94
                 North America           286192.28    259556.56   273520.78
Fashion          Asia                    266546.16    275837.98   253549.40
                 Europe                  240757.92    260801.54   291565.07
                 Middle East             263824.29    264661.41   297295.28
                 North America           265484.19    277134.01   267952.79
Home & Kitchen   Asia                    254520.35    271126.92   261576.86
                 Europe                  287782.06    243551.38   264634.03
                 Middle East             282463.59    268083.75   283679.99
                 North America           270210.76    270833.66   277193.69
Sports           Asia                    272356.66    285103.84   256409.44
                 Europe                  240316.82    269054.20   263637.83
                 Middle East             255165.94    295742.54   262467.47
                 North America           260698.11    260756.28   301921.97

payment_method                          UPI     Wallet
product_category customer_region
Beauty           Asia             248354.32  307827.07
                 Europe           266439.16  268127.68
                 Middle East      244573.85  274469.26
                 North America    257257.77  278822.81
Books            Asia             283722.70  274355.27
                 Europe           284179.33  261346.02
                 Middle East      299360.03  261296.58
                 North America    278296.04  272279.75
Electronics      Asia             296270.18  248190.20
                 Europe           289772.86  282378.00
                 Middle East      264989.76  294489.50
                 North America    273117.14  272371.10
Fashion          Asia             285787.07  252764.62
                 Europe           275522.81  297459.66
                 Middle East      288477.61  275970.01
                 North America    263212.94  315518.58
Home & Kitchen   Asia             308521.28  273931.04
                 Europe           260388.20  270068.89
                 Middle East      264839.11  276480.08
                 North America    276713.87  306533.04
Sports           Asia             285163.21  259051.93
                 Europe           257167.12  293587.23
                 Middle East      229472.47  297306.16
                 North America    297842.61  264013.99